<?php
/**
 * Created by PhpStorm.
 * User: xu
 * Date: 2017/11/30
 * Time: 16:33
 */

namespace Seller\Controller;
use Think\Controller;

class ActivityController extends CommonController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //卡劵首页
    public function index() {
        $time=date('Y-m-d H:i:s',time());
        $whereStr=" token='{$this->token}' and stoken='{$this->stoken}' and IsEnable='1'";
        $count=M()->table('RS_Coupon')->where($whereStr)->count();
        $page = new \Think\Page($count,10);
        $cards=M()->table('RS_Coupon')->where($whereStr)->field("ID,CouponId,CouponName,Rules,Count,AfterCount,CONVERT(varchar(20),CreateDate,120) as CreateDate,CONVERT(varchar(20),StartDate,120) as StartDate,CONVERT(varchar(20),ExpiredDate,120) as ExpiredDate,Type,IsShow")->limit($page->firstRow.','.$page->listRows)->order("ID desc")->select();
        $pagedata['page']=$page->show();
        $pagedata['cards']=$cards;
        $this->assign($pagedata);
        $this->display();
    }
    //保存添加的数据到数据库
    public function saveCoupon() {
        if (IS_POST) {
            $tempStr='qwertyuioplkjhgfdsazxcvbnm';
            $tempNum='1234567890';
            $tempAry=array('红包抵扣券','折扣券','满减券','摇一摇');
            $CouponId=substr(str_shuffle($tempStr),5,5).substr(str_shuffle($tempNum),5,8);
            $data['CouponName']=$tempAry[$_POST['CouponType']]; //优惠券名称
            $data['Rules']=$_POST['Rules']; //规则 type   1(抵扣金额) 2(折扣比例) 3（xx/yy)
            $data['Count']=$_POST['CouponNum']; //发行优惠券数量
            $data['AfterCount']=$_POST['CouponNum']; //剩余优惠券数量
            $data['UserCount']=1;   //用户可领取数量
            $data['Type']=$_POST['CouponType']; //0(现金抵扣) 1(折扣) 2(满xx减yy)  5大礼包
            $data['StartDate']=$_POST['StartDate']; //生效时间
            $data['ExpiredDate']=$_POST['ExpDate']; //优惠券到期时间
            $data['token']=$this->token;
            $data['stoken']=$this->stoken;
            echo "<pre>";
//            var_dump($data);die();
            if ($_POST['oldid']) {
                $data['LastUpdateDate']=date('Y-m-d H:i:s',time());
                if (M()->table('RS_Coupon')->where("ID=%d",$_POST['oldid'])->save($data)) {
                    $this->success('保存成功',U('Activity/index'));
                }else{
                    $this->error('保存失败');
                }
            }else{
                $data['CouponId']=$CouponId;
                if (M()->table('RS_Coupon')->add($data)) {
                    $this->success('保存成功',U('Activity/index'));
                }else{
                    echo M()->getlastSql();exit();
                    $this->error('保存失败');
                }
            }
        }
    }
    /**
     * 添加编辑
     */
    public function addCoupon(){
        if ($_GET['id']) {
            $info=M()->table('RS_Coupon')->where("ID=%d",$_GET['id'])->field("CONVERT(varchar(20),StartDate,120) as StartDate,CONVERT(varchar(20),ExpiredDate,120) as ExpiredDate,ID,Type,CouponName,Rules,Count,UserCount")->find();
            $pagedata['info']=$info;
        }
        $this->assign($pagedata);
        $this->display();
    }
    /**
     * 删除优惠券
     */
    public function setCoupon(){
        if (IS_POST) {
            $cid=$_POST['cid'];
            $id=$_POST['id'];
            $type=$_POST['type'];
            if ($type=='show') {
                if (M()->table('RS_Coupon')->where("ID=%d and CouponId='%s'",array($id,$cid))->setField('IsShow','1')) {
                    $msg['status']='success';
                }else{
                    $msg['status']='error';
                    $msg['info']='处理失败';
//                    var_dump(M()->getlastsql());
                }
            }elseif ($type=='del') {
                if (M()->table('RS_Coupon')->where("ID=%d and CouponId='%s'",array($id,$cid))->setField('IsEnable','0')) {
                    $msg['status']='success';
                }else{
                    $msg['status']='error';
                    $msg['info']='处理失败';
//                    var_dump(M()->getlastsql());
                }
            }
            echo json_encode($msg);
        }
    }








    public function shareredpaper(){
        if (IS_POST) {
            $type=$_POST['type'];
            $cid=$_POST['cid'];
            if ($type=='Forsharer') {
                M()->table('RS_Coupon')->where("Forsharer='1' and stoken='{$this->stoken}'")->setField('Forsharer','0');
                if (M()->table('RS_Coupon')->where("CouponId='%s'",$cid)->setField('Forsharer','1')) {
                    $msg['status']='success';
                }else{
                    $msg['status']='error';
                    $msg['info']='处理失败';
                }
            }elseif ($type=='Forshare') {
                M()->table('RS_Coupon')->where("Forshare='1' and stoken='{$this->stoken}'")->setField('Forshare','0');
                if (M()->table('RS_Coupon')->where("CouponId='%s'",$cid)->setField('Forshare','1')) {
                    $msg['status']='success';
                }else{
                    $msg['status']='error';
                    $msg['info']='处理失败';
                }
            }elseif ($type='del') {
                if ($_POST['s']=='Forshare') {
                    $name='Forshare';
                }else{
                    $name='Forsharer';
                }
                M()->table('RS_Coupon')->where("stoken='{$this->stoken}'")->setField($name,'0');
                $msg['info']=M()->getlastsql();
                $msg['status']='success';
            }
            $this->ajaxReturn($msg);
        }else{
            $Forsharer=M()->table("RS_Coupon")->where("Forsharer='1' and stoken='{$this->stoken}'")->find();
            $Forshare=M()->table("RS_Coupon")->where("Forshare='1' and stoken='{$this->stoken}'")->find();
            $pagedata['Forsharer']=$Forsharer;
            $pagedata['Forshare']=$Forshare;
            $this->assign($pagedata);
            $this->display();
        }
    }

    /**
     * 获取现金抵扣券
     */
    public function getcoupons(){
        $type=$_POST['type'];
        if ($type=='share') {
            $list=M()->table('RS_Coupon')->where("Type='2' and stoken='%s' and IsEnable='1'",$this->stoken)->field("CouponName,CouponId,Rules,CONVERT(varchar(20),StartDate,120) as StartDate,CONVERT(varchar(20),ExpiredDate,120) as ExpiredDate")->select();
            if ($list && count($list)>0) {
                $msg['status']='success';
                $msg['data']=$list;
            }else{
                $msg['status']='error';
                $msg['info']='暂无可用优惠券';
            }
        }
        $this->ajaxReturn($msg);
    }


    /**
     * 多吃优惠
     */
    public function eatmore(){
        if (IS_POST) {
            $db=$_POST;
            if ($_POST['id']) {
                //更新
                unset($db['id']);
                $db['LastUpdate']=date('Y-m-d H:i:s',time());
                $db['Lv1']=$_POST['Lv1']?$_POST['Lv1']:'';
                $db['Lv2']=$_POST['Lv2']?$_POST['Lv2']:'';
                $db['Lv3']=$_POST['Lv3']?$_POST['Lv3']:'';
                $db['Lv4']=$_POST['Lv4']?$_POST['Lv4']:'';
                $db['Lv5']=$_POST['Lv5']?$_POST['Lv5']:'';
                if (M()->table('RS_Eatmore')->where("ID=%d",$_POST['id'])->save($db)) {
                    $this->success('保存成功');
                }else{
                    $this->error('保存失败');
                    $this->LOGS("多吃优惠保存失败--->>>".M()->getlastsql());
                }
            }else{
                //添加
                unset($db['id']);
                $db['stoken']=$this->stoken;
                // var_dump($db);exit();
                if (M()->table('RS_Eatmore')->add($db)) {
                    $this->success('设置成功');
                }else{
                    $this->error('设置失败');
                    $this->LOGS("多吃优惠设置失败--->>>".M()->getlastsql());
                }

            }
        }else{
            // $prolists=M()->table('RS_Product')->where("stoken='%s'",$this->stoken)->field("ProName,ProId")->select();
            $prolists=M()->query("SELECT ProName,ProId,Price FROM RS_Product WHERE stoken='{$this->stoken}' and ProId NOT IN (SELECT ProId FROM RS_ProductOnsale WHERE stoken='{$this->stoken}')");
            $hasset=M()->query("SELECT e.*,p.ProName,p.Price FROM RS_Eatmore e LEFT JOIN RS_Product p ON e.ProId=p.ProId WHERE e.stoken='{$this->stoken}'");
            $hasstr='_';
            foreach ($hasset as $key => $value) {
                $hasstr.=$value['ProId'];
            }
            $pagedata['hasstr']=$hasstr;
            $pagedata['haslist']=$hasset;
            $pagedata['jsondata']=json_encode($hasset);
            $pagedata['prolists']=$prolists;
            $this->assign($pagedata);
            $this->display();
        }
    }

    /**
     * 多吃优惠设置
     */
    public function execeatmore(){
        $type=$_POST['type'];
        $id=$_POST['id'];
        if ($type=='del') {
            if (M()->table('RS_Eatmore')->where("ID=%d",$id)->delete()) {
                $msg['status']='success';
            }else{
                $msg['status']='error';
                $msg['info']='处理失败';
            }
        }
        $this->ajaxReturn($msg);
    }


























}
